/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRegistryAdminRouteImport } from './routes/_authenticated/registry-admin'
import { Route as AuthenticatedRegisterPropertyRouteImport } from './routes/_authenticated/register-property'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompleteProfileRouteImport } from './routes/_authenticated/complete-profile'
import { Route as AuthenticatedRegistryAdminIndexRouteImport } from './routes/_authenticated/registry-admin.index'
import { Route as AuthenticatedRegistryAdminQueueRouteImport } from './routes/_authenticated/registry-admin.queue'
import { Route as AuthenticatedRegistrationsIdRouteImport } from './routes/_authenticated/registrations.$id'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegistryAdminRoute =
  AuthenticatedRegistryAdminRouteImport.update({
    id: '/registry-admin',
    path: '/registry-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegisterPropertyRoute =
  AuthenticatedRegisterPropertyRouteImport.update({
    id: '/register-property',
    path: '/register-property',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: '/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegistryAdminIndexRoute =
  AuthenticatedRegistryAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRegistryAdminRoute,
  } as any)
const AuthenticatedRegistryAdminQueueRoute =
  AuthenticatedRegistryAdminQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => AuthenticatedRegistryAdminRoute,
  } as any)
const AuthenticatedRegistrationsIdRoute =
  AuthenticatedRegistrationsIdRouteImport.update({
    id: '/registrations/$id',
    path: '/registrations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/register-property': typeof AuthenticatedRegisterPropertyRoute
  '/registry-admin': typeof AuthenticatedRegistryAdminRouteWithChildren
  '/registrations/$id': typeof AuthenticatedRegistrationsIdRoute
  '/registry-admin/queue': typeof AuthenticatedRegistryAdminQueueRoute
  '/registry-admin/': typeof AuthenticatedRegistryAdminIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/register-property': typeof AuthenticatedRegisterPropertyRoute
  '/registrations/$id': typeof AuthenticatedRegistrationsIdRoute
  '/registry-admin/queue': typeof AuthenticatedRegistryAdminQueueRoute
  '/registry-admin': typeof AuthenticatedRegistryAdminIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/register-property': typeof AuthenticatedRegisterPropertyRoute
  '/_authenticated/registry-admin': typeof AuthenticatedRegistryAdminRouteWithChildren
  '/_authenticated/registrations/$id': typeof AuthenticatedRegistrationsIdRoute
  '/_authenticated/registry-admin/queue': typeof AuthenticatedRegistryAdminQueueRoute
  '/_authenticated/registry-admin/': typeof AuthenticatedRegistryAdminIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/complete-profile'
    | '/dashboard'
    | '/profile'
    | '/register-property'
    | '/registry-admin'
    | '/registrations/$id'
    | '/registry-admin/queue'
    | '/registry-admin/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/complete-profile'
    | '/dashboard'
    | '/profile'
    | '/register-property'
    | '/registrations/$id'
    | '/registry-admin/queue'
    | '/registry-admin'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/complete-profile'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/register-property'
    | '/_authenticated/registry-admin'
    | '/_authenticated/registrations/$id'
    | '/_authenticated/registry-admin/queue'
    | '/_authenticated/registry-admin/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/registry-admin': {
      id: '/_authenticated/registry-admin'
      path: '/registry-admin'
      fullPath: '/registry-admin'
      preLoaderRoute: typeof AuthenticatedRegistryAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/register-property': {
      id: '/_authenticated/register-property'
      path: '/register-property'
      fullPath: '/register-property'
      preLoaderRoute: typeof AuthenticatedRegisterPropertyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-profile': {
      id: '/_authenticated/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registry-admin/': {
      id: '/_authenticated/registry-admin/'
      path: '/'
      fullPath: '/registry-admin/'
      preLoaderRoute: typeof AuthenticatedRegistryAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRegistryAdminRoute
    }
    '/_authenticated/registry-admin/queue': {
      id: '/_authenticated/registry-admin/queue'
      path: '/queue'
      fullPath: '/registry-admin/queue'
      preLoaderRoute: typeof AuthenticatedRegistryAdminQueueRouteImport
      parentRoute: typeof AuthenticatedRegistryAdminRoute
    }
    '/_authenticated/registrations/$id': {
      id: '/_authenticated/registrations/$id'
      path: '/registrations/$id'
      fullPath: '/registrations/$id'
      preLoaderRoute: typeof AuthenticatedRegistrationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRegistryAdminRouteChildren {
  AuthenticatedRegistryAdminQueueRoute: typeof AuthenticatedRegistryAdminQueueRoute
  AuthenticatedRegistryAdminIndexRoute: typeof AuthenticatedRegistryAdminIndexRoute
}

const AuthenticatedRegistryAdminRouteChildren: AuthenticatedRegistryAdminRouteChildren =
  {
    AuthenticatedRegistryAdminQueueRoute: AuthenticatedRegistryAdminQueueRoute,
    AuthenticatedRegistryAdminIndexRoute: AuthenticatedRegistryAdminIndexRoute,
  }

const AuthenticatedRegistryAdminRouteWithChildren =
  AuthenticatedRegistryAdminRoute._addFileChildren(
    AuthenticatedRegistryAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRegisterPropertyRoute: typeof AuthenticatedRegisterPropertyRoute
  AuthenticatedRegistryAdminRoute: typeof AuthenticatedRegistryAdminRouteWithChildren
  AuthenticatedRegistrationsIdRoute: typeof AuthenticatedRegistrationsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRegisterPropertyRoute: AuthenticatedRegisterPropertyRoute,
  AuthenticatedRegistryAdminRoute: AuthenticatedRegistryAdminRouteWithChildren,
  AuthenticatedRegistrationsIdRoute: AuthenticatedRegistrationsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
